language: node_js

cache:
  directories:
    - node_modules

script:
  - npm run app-build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  local_dir: build
  on:
    branch: continuous-deployment
